### PR TITLE
[Mozilla Branding Removal] First pass at removing Mozilla references, links, images, etc.

### PR DESCRIPTION
**Pull request by Exairnous**
Mozilla links and references have been either removed, updated, or replaced with placeholders.  Placeholders are marked with (TBD) where possible.

The PROMOTION.md file has been rewritten to be generic and no longer conveys the automatic right to use promoted scenes in advertising.

The two images with Mozilla branding have been replaced with non-Mozilla counterparts.

More details can be found in the commit messages.

**Additional Notes:**
src/editor/nodes/TroikaTextNode.js should be checked to make sure it isn't a credit and should actually be removed.

links in .env files and habitat files are unchanged to ensure nothing breaks.  The same for references to mozillareality

links in yarn-error.log are unchanged because I think they have a historical context.  It's possible this whole file should be removed in the future, though.

The reference to Mozilla in src/ui/assets/sources/SketchfabSource.js I have deemed a credit and left unchanged.  For reference, this what I left unchanged: `label: "Mozilla Playground - by Tombolaso"`

I have left these references unchanged as I believe they don't constitute branding:
```
test/fixtures/V3TestScene.spoke:                  "href": "https://hubs.mozilla.com/scenes/VfoICgK/too-late"
test/fixtures/V4TestScene.spoke                   "href": "https://hubs.mozilla.com"
test/fixtures/V6TestScene.spoke:                  "href": "https://hubs.mozilla.com"
test/fixtures/V7TestScene.spoke:                  "href": "https://hubs.mozilla.com"
test/fixtures/V8TestScene.spoke:                  "href": "https://hubs.mozilla.com"
test/integration/Editor.test.js:                  author: "mozillareality",
test/integration/snapshots/Editor.test.js.md:     author: 'mozillareality',
test/integration/snapshots/Editor.test.js.md:     href: 'https://hubs.mozilla.com/scenes/VfoICgK/too-late',
test/integration/snapshots/Editor.test.js.md:     href: 'https://hubs.mozilla.com',
test/integration/snapshots/Editor.test.js.md:     href: 'https://hubs.mozilla.com',
test/integration/snapshots/Editor.test.js.md:     href: 'https://hubs.mozilla.com',
test/integration/snapshots/Editor.test.js.md:     href: 'https://hubs.mozilla.com',
test/integration/snapshots/Editor.test.js.md:     href: 'https://hubs.mozilla.com',
```

### CODE REVIEW

**Comment by Exairnous** [comment]
Seems the workflows won't run properly until we get a docker registry in working order.

**Comment by Exairnous** [comment]
@eyesnareinc I haven't been able to test this in hubs-compose (I can't get mine to work for some reason), but I have been able to run it locally and it does at least run (I was not able to test everything running it locally).  Maybe you could try it in your hubs-compose and see if it works?  I think it should, so I'm marking it as ready for review and requesting your review of it :)

Assuming you like the content of the PR, I think we just merge despite the failing checks once/if you give it the green light.

**Comment by Exairnous** [comment]
As discussed at a governance team meeting, I am merging this on my own recognizance.

**Comment by 56789KD** [comment]
Comment viewing Mozilla

**Pull request merged**
